export const BUY_CAKE = 'BUY_CAKE';
export const ADD_CAKE = 'ADD_CAKE';

export const BUY_ICECREAM = 'BUY_ICECREAM';
export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';



